name: Run Selenium IDE Tests and Email Report

on:
  push:
    branches: [main]

jobs:
  run-tests-and-email:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Selenium IDE Runner globally
        run: npm install -g selenium-side-runner
        shell: pwsh

      - name: Create test reports directory
        run: mkdir test-reports
        shell: pwsh

      - name: Run Selenium IDE tests with 3-min timeout
        run: selenium-side-runner --output-directory test-reports --timeout 180000 sovrn.side
        shell: pwsh
        continue-on-error: true  # So email still sends even if tests fail

      - name: Send test report via email
        uses: mikeal/sendmail@v2
        with:
          from: ${{ secrets.EMAIL_FROM }}
          to: ${{ secrets.EMAIL_TO }}
          subject: Selenium IDE Test Report - ${{ github.run_number }}
          text: |
            Hi,

            Please find attached the latest Selenium IDE test report.

            Regards,
            GitHub Actions Bot
          attachments: test-reports/*.json
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          secure: false
