name: Run Selenium IDE Tests and Email Report

on:
  push:
    branches:
      - main

jobs:
  run-tests-and-email:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Selenium IDE Runner and xml2js
        run: |
          npm install -g selenium-side-runner
          npm install xml2js

      - name: Run Selenium IDE tests
        run: selenium-side-runner --output-directory test-reports --timeout 180000 sovrn.side

      - name: Generate HTML report
        run: node generate-report-html.js

      - name: Send email with HTML report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Selenium IDE Test Report
          to: your-email@example.com
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/html
          body: |
            $(cat report.html)
