name: Run Selenium IDE .side File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Selenium IDE runner
      run: |
        npm install -g selenium-side-runner
        npm install -g chromedriver

    - name: Set Chrome path for selenium-side-runner (Windows)
      run: echo "CHROME_BIN=C:\Program Files\Google\Chrome\Application\chrome.exe" >> $GITHUB_ENV

    - name: Run Selenium IDE Test
      run: selenium-side-runner sovrn.side
