name: Run Selenium IDE Tests and Email Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-tests-and-email:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install selenium-side-runner jest jest-html-reporter
        shell: pwsh

      - name: Create reports directory
        run: mkdir test-reports
        shell: pwsh

      - name: Run Selenium IDE Tests via Jest
        run: npx jest selenium-runner.test.js --config=jest.config.js
        shell: pwsh

      - name: Send HTML report via Email
        if: always()  # Send email even if tests fail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Selenium Test Report - ${{ github.run_number }}
          to: your-email@example.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hello,

            The Selenium IDE test run has completed.
            Please find the attached test report.

            Regards,
            GitHub Actions Bot
          attachments: test-reports/test-report.html
