name: Run Selenium IDE .side File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Selenium-side-runner and ChromeDriver
      run: |
        npm install -g selenium-side-runner
        npm install -g chromedriver

    - name: Set Chrome path
      run: echo "CHROME_BIN=C:\Program Files\Google\Chrome\Application\chrome.exe" >> $GITHUB_ENV

    - name: Run Selenium IDE Test and Generate Report
      run: |
        mkdir -p test-reports
        selenium-side-runner --output-directory test-reports --output-format junit --capabilities "goog:chromeOptions.args=[headless,no-sandbox,disable-gpu,window-size=1920,1080]" sovrn.side

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: selenium-report
        path: test-reports/

    - name: Display test report summary
      if: always()
      run: |
        echo '### Selenium Test Results' >> $GITHUB_STEP_SUMMARY
        cat test-reports/*.xml >> $GITHUB_STEP_SUMMARY
