name: Run Selenium IDE Tests and Upload Report

on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Selenium IDE Runner
        run: npm install -g selenium-side-runner
        shell: pwsh

      - name: Create reports directory
        run: mkdir test-reports
        shell: pwsh

      - name: Set timestamp
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
          echo "TIMESTAMP=$timestamp" >> $env:GITHUB_ENV

      - name: Run Selenium IDE tests
        run: selenium-side-runner --output-directory test-reports sovrn.side
        shell: pwsh

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report-${{ env.TIMESTAMP }}
          path: test-reports/
