name: Run Selenium IDE Tests with Email Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Selenium IDE Runner and ChromeDriver
        run: |
          npm install -g selenium-side-runner
          npm install -g chromedriver

      - name: Set Chrome path
        run: echo "CHROME_BIN=C:\Program Files\Google\Chrome\Application\chrome.exe" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Create reports directory
        run: mkdir test-reports
        shell: pwsh

      - name: Set timestamp
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
          echo "TIMESTAMP=$timestamp" >> $env:GITHUB_ENV

      - name: Run Selenium IDE tests and generate HTML report
        # Adjust this command depending on your report generation setup!
        run: |
          selenium-side-runner --output-directory test-reports --output-format html sovrn.side
          # Rename report to include timestamp
          Rename-Item -Path test-reports\report.html -NewName "report-$env:TIMESTAMP.html"
        shell: pwsh

      - name: Upload test report as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report
          path: test-reports/report-${{ env.TIMESTAMP }}.html

      - name: Email HTML Report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Selenium Test Report - ${{ github.repository }} - ${{ env.TIMESTAMP }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hello,

            The Selenium IDE test suite has completed. Attached is the full HTML report with screenshots.

            Regards,
            GitHub Actions
          attachments: test-reports/report-${{ env.TIMESTAMP }}.html
