name: Run Selenium IDE Tests and Email PDF Report

on:
  push:
    branches: [main]

jobs:
  run-tests-and-email:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g selenium-side-runner
          npm install json2html puppeteer
        shell: pwsh

      - name: Create reports directory
        run: mkdir test-reports
        shell: pwsh

      - name: Set timestamp
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
          echo "TIMESTAMP=$timestamp" >> $env:GITHUB_ENV

      - name: Run Selenium IDE Tests
        run: selenium-side-runner --output-directory test-reports sovrn.side
        shell: pwsh

      - name: Generate PDF Report
        run: |
          node -e "
            const fs = require('fs');
            const { json2html } = require('json2html');
            const puppeteer = require('puppeteer');

            const jsonFile = fs.readdirSync('./test-reports').find(f => f.endsWith('.json'));
            const json = JSON.parse(fs.readFileSync('./test-reports/' + jsonFile, 'utf-8'));
            const htmlContent = '<h1>Selenium IDE Test Report</h1>' + json2html.render(json);

            (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.setContent(htmlContent);
              await page.pdf({ path: `selenium-report-${process.env.TIMESTAMP}.pdf`, format: 'A4' });
              await browser.close();
            })();
          "
        shell: pwsh

      - name: Send report via email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_FROM }}
          to: ${{ secrets.EMAIL_TO }}
          subject: Selenium Test Report - ${{ github.repository }}
          body: |
            Hello,

            The Selenium IDE test has completed.

            Repository: ${{ github.repository }}
            Run Timestamp: ${{ env.TIMESTAMP }}

            Please find the attached PDF test report.

            Regards,  
            GitHub Actions Bot
          attachments: selenium-report-${{ env.TIMESTAMP }}.pdf
