name: Run Selenium IDE .side File with Email Report

on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Selenium IDE Runner and ChromeDriver
        run: |
          npm install -g selenium-side-runner
          npm install -g chromedriver

      - name: Create reports directory
        run: mkdir test-reports
        shell: pwsh

      - name: Set timestamp
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
          echo "TIMESTAMP=$timestamp" >> $env:GITHUB_ENV

      - name: Run Selenium IDE Tests
        run: selenium-side-runner --timeout 180000 --output-directory test-reports sovrn.side
        shell: pwsh

      - name: Zip test report
        run: Compress-Archive -Path test-reports\* -DestinationPath test-reports\report-${{ env.TIMESTAMP }}.zip
        shell: pwsh

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-report
          path: test-reports/report-${{ env.TIMESTAMP }}.zip

      - name: Email the test report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Selenium Test Report - ${{ github.repository }} - ${{ env.TIMESTAMP }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hello,

            The Selenium IDE tests have completed successfully.

            Repository: ${{ github.repository }}
            Timestamp: ${{ env.TIMESTAMP }}

            Please find the test report attached.

            Regards,  
            GitHub Actions
          attachments: test-reports/report-${{ env.TIMESTAMP }}.zip
