name: Run Selenium IDE Tests and Email Report

on:
  push:
    branches: [main]

jobs:
  run-tests-and-email:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Selenium IDE Runner
        run: npm install -g selenium-side-runner
        shell: pwsh

      - name: Create test reports directory
        run: mkdir test-reports
        shell: pwsh

      - name: Set timestamp for reports
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
          echo "TIMESTAMP=$timestamp" >> $env:GITHUB_ENV

      - name: Run Selenium IDE tests with timeout
        run: selenium-side-runner --output-directory test-reports --timeout 180000 sovrn.side
        shell: pwsh
        continue-on-error: true  # ensures email sends even if tests fail

      - name: Compress test report
        shell: pwsh
        run: Compress-Archive -Path test-reports\* -DestinationPath selenium-report-${{ env.TIMESTAMP }}.zip

      - name: Send test report via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Selenium Test Report - Run #${{
